[book]
authors = ["BlockDeep Labs <info@blockdeep.io>"]
language = "en"
multilingual = false
src = "src"
title = "Substrate Development Best Practices"


[output.html]
additional-css = [ "style.css" ]